image: tmaier/docker-compose:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

stages:
  - test

test:
  stage: test
  script:
    - ls
    # Copy "local" env.test first
    - cp .env.local.ci .env.local
    - cat .env.test >> .env
    - rm -f docker-compose.yml || true
    - cp docker-compose-ci.yml docker-compose.yml
    - docker-compose up -d
    - docker ps
    - docker-compose logs worker
    - docker-compose exec -T worker php ./vendor/bin/phpunit
    - docker-compose stop
