image: docker:19.03.13
services:
  - name: docker:19.03.13-dind
    alias: docker
cache:
  key: ${CI_COMMIT_REF_SLUG}
  policy: pull-push

before_script:
  - docker info
  - apk add curl
  - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  - docker-compose --version
  - apk add git
  - docker-compose --version

stages:
  - test

test:
  stage: test
  only:
    - dev
  script:
    - git add . && git reset --hard
    - git pull origin dev --force
    - ls -al
    - ls
    # test runner
    # Copy "local" env.test first
    - cp .env.local.ci .env.local
    - cp .env.test.ci .env.test
    - cat .env.test.ci >> .env
    - rm -f docker-compose.yml || true
    - cp docker-compose-ci.yml docker-compose.yml
    - docker-compose up -d
    - docker ps
    #- docker-compose exec -T worker composer install
    #- docker-compose exec -T worker yarn
    - docker-compose exec -T worker chmod +x /var/www/deploy/prepare-test.sh
    - docker-compose exec -T worker /var/www/deploy/prepare-test.sh
    - docker-compose exec -T worker chmod +x /var/www/deploy/test.sh
    - docker-compose exec -T worker /var/www/deploy/test.sh
    - docker-compose stop
