<?php

namespace App\Entity\Constants;

class Activities
{
	const ACTIVITY_CEMENT_FACTORY = 1;
	const ACTIVITY_CANDY = 2;
	const ACTIVITY_DEHYDRATION = 3;
	const ACTIVITY_COVERED = 4;
	const ACTIVITY_CHEMISTRY = 5;
	const ACTIVITY_SANDPIT = 6;
	const ACTIVITY_STATIONERY = 7;
	const ACTIVITY_PORT_INDUSTRY = 8;
	const ACTIVITY_NAVAL_INDUSTRY = 9;
	const ACTIVITY_MINING_EXTRACTION = 10;
	const ACTIVITY_FOOD_INDUSTRY = 11;
	const ACTIVITY_IRON_AND_STEEL_INDUSTRY = 12;
	const ACTIVITY_WASTE = 13;
	const ACTIVITY_SUBCONTRACTING = 14;
	const ACTIVITY_ENERGY = 15;
	const ACTIVITY_OTHERS = 16;
	const ACTIVITY_CONSTRUCTOR = 17;
	const ACTIVITY_INTERMEDIARY_BUSINESS = 18;

	const ALL_ACTIVITIES = [
		self::ACTIVITY_CEMENT_FACTORY,
		self::ACTIVITY_CANDY,
		self::ACTIVITY_DEHYDRATION,
		self::ACTIVITY_COVERED,
		self::ACTIVITY_CHEMISTRY,
		self::ACTIVITY_SANDPIT,
		self::ACTIVITY_STATIONERY,
		self::ACTIVITY_PORT_INDUSTRY,
		self::ACTIVITY_NAVAL_INDUSTRY,
		self::ACTIVITY_MINING_EXTRACTION,
		self::ACTIVITY_FOOD_INDUSTRY,
		self::ACTIVITY_IRON_AND_STEEL_INDUSTRY,
		self::ACTIVITY_WASTE,
		self::ACTIVITY_SUBCONTRACTING,
		self::ACTIVITY_ENERGY,
		self::ACTIVITY_CONSTRUCTOR,
		self::ACTIVITY_INTERMEDIARY_BUSINESS,
		self::ACTIVITY_OTHERS,
	];
}